-- 1. Create table "hafazan_records"
create table if not exists hafazan_records (
  id bigint generated by default as identity primary key,
  nama_murid text not null,
  kelas text,
  tingkatan text not null,
  surah text not null,
  last_ayat text,
  nfc_id text unique,
  peratus numeric default 0,
  bintang integer default 0,
  lulus_block integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Enable realtime (optional; ignore error if already added)
-- alter publication supabase_realtime add table hafazan_records;

-- 3. RPC: register_student
create or replace function register_student(p_nama text, p_tingkatan text, p_surah text, p_kelas text, p_nfc_id text)
returns table (id bigint, nama_murid text, kelas text, tingkatan text, surah text, nfc_id text, peratus numeric, bintang integer, lulus_block integer)
language plpgsql security definer as $$
begin
  return query insert into hafazan_records (nama_murid, kelas, tingkatan, surah, nfc_id)
    values (p_nama, p_kelas, p_tingkatan, p_surah, p_nfc_id)
  returning hafazan_records.id, hafazan_records.nama_murid, hafazan_records.kelas, hafazan_records.tingkatan, hafazan_records.surah, hafazan_records.nfc_id, hafazan_records.peratus, hafazan_records.bintang, hafazan_records.lulus_block;
end;
$$;

-- 4. RPC: submit_hafazan_record
create or replace function submit_hafazan_record(
  p_murid_id bigint, p_last_ayat text, p_nfc_id text, p_status text,
  p_block integer, p_total_blocks integer, p_tingkatan text, p_surah text
) returns table (id bigint, nama_murid text, kelas text, tingkatan text, surah text, last_ayat text, nfc_id text, peratus numeric, bintang integer, lulus_block integer)
language plpgsql security definer as $$
begin
  if not exists (select 1 from hafazan_records where hafazan_records.id = p_murid_id and (nfc_id = p_nfc_id or p_nfc_id is null)) then
    raise exception 'UID kad tidak sepadan dengan murid';
  end if;
  if p_block > (select lulus_block from hafazan_records where hafazan_records.id = p_murid_id) + 1 then
    raise exception 'Blok seterusnya belum selesai';
  end if;
  update hafazan_records set last_ayat = p_last_ayat, lulus_block = greatest(hafazan_records.lulus_block, p_block),
    bintang = bintang + case when p_status = 'lancar' then 1 else 0 end,
    peratus = round((greatest(hafazan_records.lulus_block, p_block)::numeric / p_total_blocks::numeric) * 100, 0)
  where hafazan_records.id = p_murid_id;
  return query select hafazan_records.id, hafazan_records.nama_murid, hafazan_records.kelas, hafazan_records.tingkatan, hafazan_records.surah, hafazan_records.last_ayat, hafazan_records.nfc_id, hafazan_records.peratus, hafazan_records.bintang, hafazan_records.lulus_block
  from hafazan_records where hafazan_records.id = p_murid_id;
end;
$$;

-- 5. RPC: link_student_card
create or replace function link_student_card(p_murid_id bigint, p_nfc_id text)
returns void language plpgsql security definer as $$
begin
  update hafazan_records set nfc_id = p_nfc_id where hafazan_records.id = p_murid_id;
end;
$$;

-- 6. RLS + grants
alter table hafazan_records enable row level security;

drop policy if exists "allow_all_authenticated" on hafazan_records;
create policy "allow_all_authenticated" on hafazan_records
  for all to authenticated using (true) with check (true);

-- Jika mahu akses anon (tanpa login), buka komen baris di bawah:
-- drop policy if exists "allow_all_anon" on hafazan_records;
-- create policy "allow_all_anon" on hafazan_records
--   for all to anon using (true) with check (true);

grant usage on schema public to authenticated, anon;
grant all on hafazan_records to authenticated, anon;
grant execute on function register_student(text, text, text, text, text) to authenticated, anon;
grant execute on function submit_hafazan_record(bigint, text, text, text, integer, integer, text, text) to authenticated, anon;
grant execute on function link_student_card(bigint, text) to authenticated, anon;
